name: Worker

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  deployWorker:
    name: Deploy Worker in Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
          
     - name: Setting Vars
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku config:set POSTGRES_URI=${{ secrets.POSTGRES_URI }} -a tp-worker
          heroku config:set REDIS_PORT=${{ secrets.REDIS_PORT }} -a tp-worker
          heroku config:set REDIS_HOST=${{ secrets.REDIS_HOST }} -a tp-worker
          heroku config:set REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} -a tp-worker
     
      - name: Build and Push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd ./worker
          heroku container:push -a tp-worker web
          
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a tp-worker web 
